name: CI/CD to production

on:
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: read
  id-token: write

jobs:
  build_and_test:
    uses: ./.github/workflows/test.yml
  
  build_and_push_docker_image:
    needs: build_and_test
    uses: ./.github/workflows/build-docker.yml
    with:
      PROJECT_ID_ARTIFACT_REGISTRY: vl-bots-common/vl-reportbot-prod-repository
      REGION: europe-west1
      SERVICE: reportbot-prod
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER_PROD }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT_PROD }}
  
  deploy_to_prod:
    needs: build_and_push_docker_image
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      PROJECT_ID_ARTIFACT_REGISTRY: vl-bots-common/vl-reportbot-prod-repository
      SERVICE: reportbot-prod
      PROJECT_ID_CLOUD_RUN: vl-bots-reportbot-prod
      REGION: europe-west1
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER_PROD }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.WIF_SERVICE_ACCOUNT_PROD }}
  